Repository SmithNola/QuizGenerator, pull requests merged in 2020-07, with the labels that each got.

#68 Created tests for LoginDoesNotExists
  pom.xml
  src/main/java/org/quizgen/controller/LoginController.java
  src/main/java/org/quizgen/controller/SignUpController.java
  src/main/java/org/quizgen/data/DatabaseConnection.java
  src/main/java/org/quizgen/utils/authentication/AccountError.java
  src/main/java/org/quizgen/utils/authentication/HashPassword.java
  src/main/java/org/quizgen/utils/authentication/LoginValidation.java
  src/main/java/org/quizgen/utils/authentication/PasswordPolicy.java
  src/main/java/org/quizgen/utils/authentication/SignupAuth.java
  src/main/java/org/quizgen/utils/encryption/HashPassword.java
  src/main/java/org/quizgen/utils/login/AccountValidator.java
  src/main/java/org/quizgen/utils/login/PasswordValidator.java
  src/main/java/org/quizgen/utils/signup/UsernameValidator.java
  src/test/java/utils/authentication/HashPasswordTest.java
  src/test/java/utils/authentication/LoginValidationTest.java
  src/test/java/utils/authentication/SignUpValidationTest.java
Labels: Tests

#73 Small refactoring
  pom.xml
  src/main/db/QuizGen.db
  src/main/java/module-info.java
  src/main/java/org/quizgen/Main.java
  src/main/java/org/quizgen/QuizGenApp.java
  src/main/java/org/quizgen/controller/CreatingController.java
  src/main/java/org/quizgen/controller/DisplayQuizzesController.java
  src/main/java/org/quizgen/controller/EditingController.java
  src/main/java/org/quizgen/controller/HomePageController.java
  src/main/java/org/quizgen/controller/LoginController.java
  src/main/java/org/quizgen/controller/PlayingController.java
  src/main/java/org/quizgen/controller/QuizInfoController.java
  src/main/java/org/quizgen/controller/QuizSettingsController.java
  src/main/java/org/quizgen/controller/ScoreController.java
  src/main/java/org/quizgen/controller/SignUpController.java
  src/main/java/org/quizgen/controller/StartPageController.java
  src/main/java/org/quizgen/domain/authentication/AuthError.java
  src/main/java/org/quizgen/domain/authentication/LoginAuth.java
  src/main/java/org/quizgen/domain/authentication/PasswordAuth.java
  src/main/java/org/quizgen/domain/authentication/PasswordHash.java
  src/main/java/org/quizgen/domain/authentication/SignupAuth.java
  src/main/java/org/quizgen/domain/playing/AnswerChecker.java
  src/main/java/org/quizgen/domain/quizCreation/SaveQuiz.java
  src/main/java/org/quizgen/domain/scenehandling/SceneLoader.java
  src/main/java/org/quizgen/domain/scenehandling/SceneTransition.java
  src/main/java/org/quizgen/domain/scenehandling/Views.java
  src/main/java/org/quizgen/domain/viewQuizzes/DisplayQuiz.java
  src/main/java/org/quizgen/utils/SceneLoader.java
  src/test/java/utils/authentication/LoginAuthTest.java
  src/test/java/utils/authentication/PasswordAuthTest.java
  src/test/java/utils/authentication/PasswordHashTest.java
  src/test/java/utils/authentication/SignUpAuthValidationTest.java
Labels: Refactoring

#76 Allows user to add new questions and choices when editing
  src/main/java/org/quizgen/controller/CreatingController.java
  src/main/java/org/quizgen/controller/EditingController.java
  src/main/java/org/quizgen/controller/PlayingController.java
  src/main/java/org/quizgen/controller/ScoreController.java
  src/main/java/org/quizgen/data/DatabaseConnection.java
  src/main/java/org/quizgen/domain/playing/AnswerChecker.java
  src/main/java/org/quizgen/domain/quizCreation/SaveQuiz.java
  src/main/java/org/quizgen/model/Choice.java
  src/main/java/org/quizgen/model/Question.java
  src/main/java/org/quizgen/model/Quiz.java
Labels: Editing

#77 Some Code Refactoring
  src/main/java/org/quizgen/controller/CreatingController.java
  src/main/java/org/quizgen/controller/DisplayQuizzesController.java
  src/main/java/org/quizgen/controller/EditingController.java
  src/main/java/org/quizgen/controller/HomePageController.java
  src/main/java/org/quizgen/controller/LoginController.java
  src/main/java/org/quizgen/controller/PlayingController.java
  src/main/java/org/quizgen/controller/QuizInfoController.java
  src/main/java/org/quizgen/controller/QuizSettingsController.java
  src/main/java/org/quizgen/controller/ResetPasswordController.java
  src/main/java/org/quizgen/controller/ScoreController.java
  src/main/java/org/quizgen/controller/SignUpController.java
  src/main/java/org/quizgen/controller/StartPageController.java
  src/main/java/org/quizgen/data/DatabaseConnection.java
  src/main/java/org/quizgen/domain/CustomGUI.java
  src/main/java/org/quizgen/domain/playing/AnswerChecker.java
  src/main/java/org/quizgen/domain/quizCreation/SaveQuiz.java
  src/main/java/org/quizgen/domain/scenehandling/SceneTransition.java
  src/main/java/org/quizgen/domain/viewQuizzes/DisplayQuiz.java
  src/main/java/org/quizgen/model/Choice.java
  src/main/java/org/quizgen/model/Question.java
  src/main/java/org/quizgen/model/Quiz.java
  src/main/resources/fxml/login.fxml
  src/main/resources/fxml/resetPassword.fxml
  src/main/resources/fxml/signUp.fxml
  src/test/java/utils/authentication/PasswordAuthTest.java
Labels: Refactoring

#80 Added design to QuizInfo
  src/main/java/org/quizgen/controller/QuizInfoController.java
  src/main/resources/fxml/quizInfo.fxml
  src/main/resources/stylesheet/quizinfosheet.css
Labels: QuizInfo

#82 Minimized methods, organized code
  src/main/java/org/quizgen/controller/CreatingController.java
  src/main/java/org/quizgen/controller/EditingController.java
  src/main/java/org/quizgen/controller/PlayingController.java
  src/main/java/org/quizgen/controller/QuizSettingsController.java
  src/main/java/org/quizgen/controller/ScoreController.java
  src/main/java/org/quizgen/controller/StartPageController.java
  src/main/java/org/quizgen/domain/answers/AnswerChecker.java
  src/main/java/org/quizgen/domain/errors/AlertMessages.java
  src/main/java/org/quizgen/domain/errors/Alerts.java
  src/main/resources/fxml/quizInfo.fxml
  src/main/resources/fxml/quizSettings.fxml
Labels: Refactoring

#84 User can now see the amount of times a quiz has been played
  src/main/java/org/quizgen/controller/QuizInfoController.java
  src/main/java/org/quizgen/data/DatabaseConnection.java
  src/main/java/org/quizgen/model/Quiz.java
  src/main/resources/fxml/quizInfo.fxml
Labels: QuizInfo
